# Starter pipeline
- task: SpecFlowPlus@0
  inputs:
    generatorSource: 'FeatureFolder'
    projectFilePath: 'SpecFlowProject'
    projectName: 'SpecFlowProject'
    testExecutionJson: 'SpecFlowProject\bin\Debug\net.5.0\TestExecution.json'
    projectLanguage: 'en'
    bindingAssemblies: 'SpecFlowProject\bin\Debug\net.5.0\SpecFlowProject.dll'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
